### ISSUE TITLE
Error  python airbnb.py -dbp -c root.config

### ISSUE THREAD

**Issue by diouck** [tomslee/airbnb-data-collection#19]
Hello how to solve this problem I have already parameterize the config file for postgresql

Root @ ubuntu-srv1: / var / lib / tomcat7 / airbnb-data-collection-master #python airbnb.py -dbp -c root.config
No handlers could be found for logger "root"
Traceback (most recent call last):
  File "airbnb.py", line 479, in <module>
    hand()
  File "airbnb.py", line 417, in main
    Ab_config = ABConfig (args)
  File "/var/lib/tomcat7/airbnb-data-collection-master/airbnb_config.py", line 69, in __init__
    Logger.warning ("No proxy_list in" + config_file + ": not using proxies")
NameError: global name 'config_file' is not defined

**Comment by tomslee** [comment]
Hi @diouck:

That looks like an error message from an earlier build. I just updated the master branch and it works for me

`[ec2-user@ip-172-30-1-102 airbnb-data-collection]$ ./airbnb.py -dbp -c country.config`
`Connection test succeeded`

Can you confirm if it is still happening for you with the most recent build (master branch)?

**Comment by diouck** [comment]
I download the master branch directly but I do not know where the error came from

**Comment by diouck** [comment]
Now my error is : no handlers could be found for logger "root"

**Comment by tomslee** [comment]
I hope the master branch is now tidied up: I have been testing it extensively over the last while. I will avoid doing development on master from now on, and try to keep it more stable.

**Comment by Luisbalmeida** [comment]
I have one error 

C:\airbnb>python airbnb.py -dbp -c user.config
ERROR:root:Failed to read config file properly
Traceback (most recent call last):
  File "C:\airbnb\airbnb_config.py", line 79, in __init__
    self.HTTP_PROXY_LIST = config["NETWORK"]["proxy_list"].split(",")
  File "C:\python\lib\configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'proxy_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\airbnb\airbnb_config.py", line 82, in __init__
    logger.warning("No proxy_list in " + config_file + ": not using proxies")
NameError: name 'config_file' is not defined
Traceback (most recent call last):
  File "C:\airbnb\airbnb_config.py", line 79, in __init__
    self.HTTP_PROXY_LIST = config["NETWORK"]["proxy_list"].split(",")
  File "C:\python\lib\configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'proxy_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airbnb.py", line 482, in <module>
    main()
  File "airbnb.py", line 423, in main
    ab_config = ABConfig(args)
  File "C:\airbnb\airbnb_config.py", line 82, in __init__
    logger.warning("No proxy_list in " + config_file + ": not using proxies")
NameError: name 'config_file' is not defined

C:\airbnb>



[userconfig.txt](https://github.com/tomslee/airbnb-data-collection/files/1342705/userconfig.txt)
