### ISSUE TITLE
Default Config selection

### ISSUE THREAD

**Issue by loasishospitality** [tomslee/airbnb-data-collection#41]
Is it possible to switch default config file selection to any file with .config extension ? Or any other suggestion

For Docker dev-alpine branch, database host, name, password and port are prefilled in docker/configs/docker.config.example

User environment variable doesn't seem to work in Alpine linux :

`ERROR   Failed to read config file properly
Traceback (most recent call last):
  File "/home/jovyan/work/collector/airbnb_config.py", line 61, in __init__
    username = os.environ['USER']
  File "/opt/conda/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'USER'
Traceback (most recent call last):
  File "airbnb.py", line 563, in <module>
    main()
  File "airbnb.py", line 497, in main
    ab_config = ABConfig(args)
  File "/home/jovyan/work/collector/airbnb_config.py", line 61, in __init__
    username = os.environ['USER']
  File "/opt/conda/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'USER'
`

**Comment by tomslee** [comment]
There is a -c <config-file> option. Would that do the trick?

**Comment by loasishospitality** [comment]
Yes -c docker.config works well - The ideal goal is to bring the tool almost ready-to-use with docker
Found a turnaround passing USER variable through docker-compose file
